#!/bin/bash
LOG_FILE="/var/log/robot-zoo.log"

generate_report() {
    date_str=$(date -d '0 day ago' '+%Y-%m-%d')
    echo "Subject: Robot zoo log for $date_str"
    echo "To: $1"
    echo "Content-Type: text/html"
    echo
    echo "<body><code><pre>"
    grep "^$date_str" $LOG_FILE
    echo "</pre></code></body>"
}

if [ $# -eq 0 ]; then
    generate_report "test@example.com"
else
    generate_report "$1" | sendmail "$1"
fi
